[build-system]
requires = [
    "numpy",
    "cmdstanpy",
    "pystan",
    "pandas",
    "scipy",
    "statsmodels",
    "sklearn",
    "matplotlib",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
